# Generated by Django 3.1.4 on 2020-12-29 20:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('programs', '0007_auto_20201229_2311'),
    ]

    operations = [
        migrations.CreateModel(
            name='TrainingHistory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('success', models.BooleanField(default=True)),
                ('program', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='programs.program')),
            ],
        ),
        migrations.CreateModel(
            name='TrainigPlan',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Schedule',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('weekday', models.PositiveIntegerField(choices=[(0, 'Понедельник'), (1, 'Вторник'), (2, 'Среда'), (3, 'Четверг'), (4, 'Пятница'), (5, 'Суббота'), (6, 'Воскресенье')])),
                ('program', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='programs.program')),
                ('training_plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='plans.trainigplan')),
            ],
        ),
    ]
