# Generated by Django 3.1.4 on 2021-01-05 17:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('plans', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='TrainingHistory',
        ),
    ]
