# Generated by Django 3.1.5 on 2021-02-12 21:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('plans', '0002_delete_traininghistory'),
    ]

    operations = [
        migrations.RenameField(
            model_name='schedule',
            old_name='program',
            new_name='training',
        ),
    ]
