# Generated by Django 3.1.4 on 2021-01-05 17:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('programs', '0008_auto_20210105_2012'),
    ]

    operations = [
        migrations.CreateModel(
            name='TrainingHistory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='ExerciseDone',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('repeats', models.IntegerField()),
                ('exercise', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='programs.exercise')),
                ('training_history', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='training_history.traininghistory')),
            ],
        ),
    ]
