# Generated by Django 3.1.4 on 2021-01-05 17:43

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('programs', '0008_auto_20210105_2012'),
        ('training_history', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='traininghistory',
            name='date',
        ),
        migrations.AddField(
            model_name='traininghistory',
            name='end',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='traininghistory',
            name='program',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.PROTECT, to='programs.program'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='traininghistory',
            name='start',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
