# Generated by Django 3.1.5 on 2021-02-12 21:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('training_history', '0004_auto_20210107_1235'),
    ]

    operations = [
        migrations.RenameField(
            model_name='traininghistory',
            old_name='program',
            new_name='training',
        ),
    ]
