# Generated by Django 3.1.4 on 2020-12-29 19:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('programs', '0002_auto_20201229_2154'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exercise',
            name='weight',
            field=models.DecimalField(decimal_places=2, max_digits=5),
        ),
        migrations.AlterField(
            model_name='exercisehistory',
            name='weight',
            field=models.DecimalField(decimal_places=2, max_digits=5),
        ),
    ]
