# Generated by Django 3.1.4 on 2020-12-29 19:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('programs', '0003_auto_20201229_2213'),
    ]

    operations = [
        migrations.AddField(
            model_name='exercise',
            name='approaches',
            field=models.PositiveSmallIntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='exercise',
            name='repeats',
            field=models.PositiveSmallIntegerField(default=1),
        ),
    ]
