# Generated by Django 3.1.4 on 2020-12-29 19:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('programs', '0004_auto_20201229_2216'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='exercise',
            options={'ordering': ['program_id', 'order']},
        ),
        migrations.AddField(
            model_name='exercise',
            name='order',
            field=models.PositiveSmallIntegerField(default=1, verbose_name='Порядковый номер'),
        ),
        migrations.AddField(
            model_name='exercise',
            name='program',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='programs.program', verbose_name='Программа'),
        ),
        migrations.AlterField(
            model_name='exercise',
            name='approaches',
            field=models.PositiveSmallIntegerField(default=1, verbose_name='Подходов'),
        ),
        migrations.AlterField(
            model_name='exercise',
            name='inventory',
            field=models.IntegerField(choices=[(0, 'None'), (1, 'Neck'), (2, 'Dumbbell'), (3, 'Kettlebell')], default=0, verbose_name='Инвентарь'),
        ),
        migrations.AlterField(
            model_name='exercise',
            name='name',
            field=models.CharField(max_length=150, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='exercise',
            name='repeats',
            field=models.PositiveSmallIntegerField(default=1, verbose_name='Повторений'),
        ),
        migrations.AlterField(
            model_name='exercise',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Обновлено'),
        ),
        migrations.AlterField(
            model_name='exercise',
            name='weight',
            field=models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Вес'),
        ),
    ]
