# Generated by Django 3.1.4 on 2020-12-29 19:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('programs', '0005_auto_20201229_2228'),
    ]

    operations = [
        migrations.AddField(
            model_name='exercisehistory',
            name='approaches',
            field=models.PositiveSmallIntegerField(default=0),
            preserve_default=False,
        ),
    ]
