# Generated by Django 3.1.4 on 2020-12-29 20:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('programs', '0006_exercisehistory_approaches'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exercise',
            name='inventory',
            field=models.IntegerField(choices=[(0, 'Ничего'), (1, 'Штанга'), (2, 'Гантели'), (3, 'Гиря')], default=0, verbose_name='Инвентарь'),
        ),
    ]
