# Generated by Django 3.1.4 on 2021-01-05 17:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('programs', '0007_auto_20201229_2311'),
    ]

    operations = [
        migrations.RenameField(
            model_name='program',
            old_name='rest_between_sets',
            new_name='rest_between_repeats',
        ),
    ]
