# Generated by Django 3.1.5 on 2021-02-12 21:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('programs', '0010_auto_20210213_0007'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='exercise',
            options={'ordering': ['training_id', 'order']},
        ),
        migrations.RemoveField(
            model_name='exercise',
            name='program',
        ),
        migrations.AddField(
            model_name='exercise',
            name='training',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='programs.training', verbose_name='Тренировка'),
        ),
    ]
