# Generated by Django 3.1.5 on 2021-02-26 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('programs', '0012_auto_20210214_1713'),
    ]

    operations = [
        migrations.CreateModel(
            name='HelpForFriend',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='')),
            ],
        ),
    ]
